// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD4e6690eDecodeYulaInternalModels(in *jlexer.Lexer, out *ImageCompressorConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "PathToDir":
			if in.IsNull() {
				in.Skip()
				out.PathToDir = nil
			} else {
				in.Delim('[')
				if out.PathToDir == nil {
					if !in.IsDelim(']') {
						out.PathToDir = make([]string, 0, 4)
					} else {
						out.PathToDir = []string{}
					}
				} else {
					out.PathToDir = (out.PathToDir)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.PathToDir = append(out.PathToDir, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Start":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Start).UnmarshalJSON(data))
			}
		case "EveryHours":
			out.EveryHours = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD4e6690eEncodeYulaInternalModels(out *jwriter.Writer, in ImageCompressorConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"PathToDir\":"
		out.RawString(prefix[1:])
		if in.PathToDir == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.PathToDir {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Start\":"
		out.RawString(prefix)
		out.Raw((in.Start).MarshalJSON())
	}
	{
		const prefix string = ",\"EveryHours\":"
		out.RawString(prefix)
		out.Int(int(in.EveryHours))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ImageCompressorConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD4e6690eEncodeYulaInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ImageCompressorConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD4e6690eEncodeYulaInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ImageCompressorConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD4e6690eDecodeYulaInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ImageCompressorConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD4e6690eDecodeYulaInternalModels(l, v)
}
