// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	auth "yula/proto/generated/auth"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// AuthClient is an autogenerated mock type for the AuthClient type
type AuthClient struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx, in, opts
func (_m *AuthClient) Check(ctx context.Context, in *auth.SessionID, opts ...grpc.CallOption) (*auth.Result, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *auth.Result
	if rf, ok := ret.Get(0).(func(context.Context, *auth.SessionID, ...grpc.CallOption) *auth.Result); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *auth.SessionID, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *AuthClient) Create(ctx context.Context, in *auth.UserID, opts ...grpc.CallOption) (*auth.Result, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *auth.Result
	if rf, ok := ret.Get(0).(func(context.Context, *auth.UserID, ...grpc.CallOption) *auth.Result); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *auth.UserID, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, in, opts
func (_m *AuthClient) Delete(ctx context.Context, in *auth.SessionID, opts ...grpc.CallOption) (*auth.Nothing, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *auth.Nothing
	if rf, ok := ret.Get(0).(func(context.Context, *auth.SessionID, ...grpc.CallOption) *auth.Nothing); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Nothing)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *auth.SessionID, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
