// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "yula/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: sess
func (_m *SessionRepository) Delete(sess *models.Session) error {
	ret := _m.Called(sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Session) error); ok {
		r0 = rf(sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByValue provides a mock function with given fields: value
func (_m *SessionRepository) GetByValue(value string) (*models.Session, error) {
	ret := _m.Called(value)

	var r0 *models.Session
	if rf, ok := ret.Get(0).(func(string) *models.Session); ok {
		r0 = rf(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: sess
func (_m *SessionRepository) Set(sess *models.Session) error {
	ret := _m.Called(sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Session) error); ok {
		r0 = rf(sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
