name: deploy

on:
  push:
    branches:
      - main
      - dev
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      # установка либы для работы с картинками
      - script: |
        sudo apt-get install libjpeg-dev
        sudo apt-get install libpng-dev
        sudo apt-get install libwebp-dev
        curl -o ./vips-8.12.1.tar.gz "https://github.com/libvips/libvips/releases/download/v8.12.1/vips-8.12.1.tar.gz"
        tar xf vips-8.12.0-rc1.tar.gz
        cd vips-8.12.0/
        ./configure --with-png-includes --with-png-libraries --with-jpeg-includes --with-jpeg-libraries
        make
        sudo make install
        sudo ldconfig

      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run test with cover
        run: cd internal/ | go test -coverpkg=./... -coverprofile=cover ./... && cat cover | grep -v "mock" | grep -v  "easyjson" | grep -v "proto" > cover.out && go tool cover -func=cover.out

  build:
    name: Build Docker
    # needs: test потом расскоментить
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push db
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/db/Dockerfile
          platforms: linux/amd64
          push: true
          tags: decadanceeeee/2021_2_frontoviki_db:latest
      - name: Build and push tarantool
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/tarantool/Dockerfile
          platforms: linux/amd64
          push: true
          tags: decadanceeeee/2021_2_frontoviki_tarantool:latest
      - name: Build and push auth
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/auth/Dockerfile
          platforms: linux/amd64
          push: true
          tags: decadanceeeee/2021_2_frontoviki_auth:latest
      - name: Build and push chat
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/chat/Dockerfile
          platforms: linux/amd64
          push: true
          tags: decadanceeeee/2021_2_frontoviki_chat:latest
      - name: Build and push category
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/category/Dockerfile
          platforms: linux/amd64
          push: true
          tags: decadanceeeee/2021_2_frontoviki_category:latest
      - name: Build and push main
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/main/Dockerfile
          platforms: linux/amd64
          push: true
          tags: decadanceeeee/2021_2_frontoviki_main:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pull docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/zennoma/deploy_backend
            cat password.txt | sudo -S docker pull decadanceeeee/2021_2_frontoviki_main:latest
            cat password.txt | sudo -S docker pull decadanceeeee/2021_2_frontoviki_chat:latest
            cat password.txt | sudo -S docker pull decadanceeeee/2021_2_frontoviki_category:latest
            cat password.txt | sudo -S docker pull decadanceeeee/2021_2_frontoviki_auth:latest
            cat password.txt | sudo -S docker pull decadanceeeee/2021_2_frontoviki_tarantool:latest
            cat password.txt | sudo -S docker pull decadanceeeee/2021_2_frontoviki_db:latest
      - name: deploy docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/zennoma/deploy_backend
            cat password.txt | sudo -S docker-compose up -d