global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'golang'
    static_configs:
      - targets: ['127.0.0.1:5000']

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9091