global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'
    scheme: https
    tls_config:
      insecure_skip_verify: true
      ca_file: selfsigned.crt
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'golang'
    scheme: https
    tls_config:
      insecure_skip_verify: true
      ca_file: selfsigned.crt
    static_configs:
      - targets: ['127.0.0.1:5000']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9091